### ISSUE TITLE
Eliminate dependency on google.golang.org/api/iterator

### ISSUE THREAD

**Issue by sergey-a-berezin** [stockparfait/stockparfait#22]
I started out using `google.golang.org/api/iterator` and the idea of `Next() (valueType, error)` method implementing an iterator, but it turns out it pulls in a gazillion of irrelevant packages, all for a single value of `iterator.Done`.

I'm also not happy with returning a special `error` value to indicate the iterator is done, since this error may potentially be returned by the underlying generator.

Therefore, I'd like to redefine my iterator pattern to be of the form:

```go
func Next() (ok bool, v valueType)
```

If a generator needs to return its own errors, it should wrap it into the `valueType`, which could be a `struct`. The iterator is clearly done when `ok` is `false`, it is simple and still somewhat similar to the Google Cloud iterators, except that this pattern doesn't require any external package.

The `valueType` may be `error`, and for that reason `ok` is placed first, since `staticcheck` style check insists that an `error` should be returned last.

However, if an iterator may terminate with its own error, the `ok bool` result may be replaced by `err error`, in which case it may need to be placed after the value. In this case, the iterator's end must be indicated by a special error value.

**Comment by dominikh** [comment]
> since staticcheck style check insists that an error should be returned last.

Note that Staticcheck 2022.1 allows `(..., error, bool)` and won't insist on the error coming after the bool.

**Comment by sergey-a-berezin** [comment]
The linked stockparfait/parallel#3 will resolve this issue, closing it here.
